[phases.setup]
nixPkgs = ['php81', 'php81Packages.composer', 'nodejs_18']

[phases.install]
cmds = ['composer install --optimize-autoloader --no-dev --no-interaction']

[phases.build]
cmds = ['npm install && npm run build']

[start]
cmd = 'php artisan serve --host 0.0.0.0 --port $PORT'